// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/iot/aksk.ts";
import * as $1 from "./routes/api/iot/devices/[deviceId]/properties.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/main.tsx";
import * as $$0 from "./islands/device.tsx";
import * as $$1 from "./islands/sign-form.tsx";

const manifest = {
  routes: {
    "./routes/api/iot/aksk.ts": $0,
    "./routes/api/iot/devices/[deviceId]/properties.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/main.tsx": $3,
  },
  islands: {
    "./islands/device.tsx": $$0,
    "./islands/sign-form.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
